### ISSUE TITLE
Decide what the default behavior of bgpreader should be

### ISSUE THREAD

**Issue by alistairking** [CAIDA/libbgpstream#129]
Do we want bgpreader with no args to give all data? Only stream data? Output help information?

Currently it uses the broker DI and gets all data (stream and batch) from now onwards, however I often run bgpreader with no args and expect to see the help info, so once we have the resource type option exposed (#128) we could change the behavior so that no args prints help, then one can add resource type option(s) to get live (and possibly batch) data.

**Comment by albertocaida** [comment]
Yeah let's have it output help information.
