### ISSUE TITLE
bgpreader only reads last upd-file argument

### ISSUE THREAD

**Issue by cmosig** [CAIDA/libbgpstream#173]
The help page says:
```
 -o, --data-interface-option  
                       <option-name>=<option-value>*
```
and
```
* denotes an option that can be given multiple times
```

I am trying the following query: `bgpreader -d singlefile -o upd-file=A.bz2 -o upd-file=B.bz2`

The output is the same as: `bgpreader -d singlefile -o upd-file=B.bz2`
(A.bz2 is not an empty file.)

This means that all -o parameters are ignored except the last one. Probably because all previous ones are being overwritten.

**Comment by alistairking** [comment]
The "multiple times" refers to the data interface option (`-o`) option, not to the `upd-file` option-name parameter to the `-o` option.

I know, confusing.

For example, `-o upd-file=updates.gz -o rib-file=rib.gz` should work as expected.

If you want to take a stab at improving the bgpreader help output to clarify this that would be much appreciated.
