### ISSUE TITLE
3 route-views route collectors missing

### ISSUE THREAD

**Issue by cmosig** [CAIDA/libbgpstream#189]
These route-views projects are not available when using the bgpreader:

```
route-views2.saopaulo
route-views.rio
route-views.fortaleza
```

Probably because they are fairly new and have not been added yet.

**Comment by alistairking** [comment]
Thanks for the reminder.

We added the following collectors this morning:
```
route-views2.saopaulo
route-views.rio
route-views.fortaleza
route-views.phoix
route-views.gorex
route-views.gixa
```
All archived data should be available for each collector (saopaulo indexing is still running, but should finish soon).
