### ISSUE TITLE
Option to disable certificate validation

### ISSUE THREAD

**Issue by cmosig** [CAIDA/libbgpstream#190]
It would be nice to have the option to disable certificate validation. At the moment Isolario's SSL certificate expired and therefore the bgpreader fails to download these files. I know this isn't a bgpreader issue, but this option would be "nice to have".  

```
$ bgpreader -w 1574208000,1574218800 -t updates -d singlefile -o upd-file=https://www.isolario.it/Isolario_MRT_data/Taris/2019_11/updates.20191120.0300.bz2 
HTTP ERROR: SSL peer certificate or SSH remote key was not OK (60)
2020-05-17 16:44:27 778855: bsdi_singlefile.c:146: ERROR: can't open file 'https://www.isolario.it/Isolario_MRT_data/Taris/2019_11/updates.20191120.0300.bz2'
                                                                  
```

Are there any options I can set myself to temporarily resolve this issue?

Thanks! :)

**Comment by digizeph** [comment]
@cmosig you can try rebuild `libwandio` with `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` set to zero, and then rebuild libbgpstream.

- https://github.com/wanduow/wandio/blob/33e94742a53e8b59a56b46f347107170888ccf2e/lib/ior-http.c#L299 -> `curl_easy_setopt(DATA(io)->curl, CURLOPT_SSL_VERIFYPEER, 0L);`
- https://github.com/wanduow/wandio/blob/33e94742a53e8b59a56b46f347107170888ccf2e/lib/ior-http.c#L300 -> `curl_easy_setopt(DATA(io)->curl, CURLOPT_SSL_VERIFYHOST, 0L);`

**Comment by cmosig** [comment]
Thanks a lot, this worked!
