### ISSUE TITLE
Seven RouteViews collectors missing

### ISSUE THREAD

**Issue by phenschke** [CAIDA/libbgpstream#226]
Hi,

I just went through the RouteViews collector list, comparing it with the ones available through the BGPStream broker and found seven recent collector additions that the broker doesn't yet track. 
```
route-views.ny (added 11.2021)
route-views.uaeix (added 08.2021)
route-views.bknix (added 10.2019)
route-views.bdix (added 04.2021)
route-views.siex (added 06.2021)
route-views.peru (added 06.2021)
route-views5 (added 09.2021)
```
It would be great if these collectors were added. 
Thanks for the great work!

**Comment by alistairking** [comment]
Thanks for letting us know!
These should be all up and running now.
