### ISSUE TITLE
Requesting support for Debian bullseye

### ISSUE THREAD

**Issue by ralphholz** [CAIDA/libbgpstream#229]
Hi,

The instructions on https://bgpstream.caida.org/docs/install/bgpstream do not work for Debian bullseye. The install scripts add add a repo https://pkg.caida.org/os/debian/dists/bullseye/main to /etc/apt/sources.list.d/caida, but this repo does not actually exist yet -> you get a 404.

One could probably try to downgrade to buster or build from source, but support for bullseye would be much appreciated.

**Comment by mikrologic** [comment]
+1

**Comment by jtkristoff** [comment]
And now bookworm is available.  In `/etc/apt/sources.list.d/caida.list` I just set the distro to buster instead of bookworm, seems to fine for now.

**Comment by brendonj** [comment]
Packages have now been built for Debian Bullseye (as well as Debian Bookworm and Ubuntu Jammy) and are available in the CAIDA package repository. If you still have the repository configured then you should be able to refresh the package index and install the package: `sudo apt-get update && sudo apt-get install bgpstream`. Let me know if you still have issues getting packages.
