### ISSUE TITLE
Executing autogen.sh fails in Ubuntu 22.04

### ISSUE THREAD

**Issue by ACodingfreak** [CAIDA/libbgpstream#231]
Trying fresh install in Ubuntu 22.04 by executing autogen.sh which fails with below error.

> libbgpstream$ ./autogen.sh 
> Initializing submodules
> Running autoconf
> autoreconf: export WARNINGS=
> autoreconf: Entering directory '.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I m4
> configure.ac:65: error: AM_INIT_AUTOMAKE expanded multiple times
> /usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
> configure.ac:49: the top level
> /usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
> configure.ac:65: the top level
> autom4te: error: /usr/bin/m4 failed with exit status: 1
> aclocal: error: /usr/bin/autom4te failed with exit status: 1
> autoreconf: error: aclocal failed with exit status: 1

**Comment by ACodingfreak** [comment]
Looks like an issue with automake 1.16.5 

Similar issues in other opensource projects 

[https://patchwork.ozlabs.org/project/buildroot/patch/20211015062208.201342-1-fontaine.fabrice@gmail.com/](https://patchwork.ozlabs.org/project/buildroot/patch/20211015062208.201342-1-fontaine.fabrice@gmail.com/)

**Comment by brendonj** [comment]
This should now be fixed by 2bce0f679c1703ef154588782af250ccd30c012e, which is part of the 2.3.0 release. Let me know if you still have issues with the latest release.
