### ISSUE TITLE
Install for mac wandio timeout

### ISSUE THREAD

**Issue by jes089** [CAIDA/libbgpstream#237]
1. From `2. Download and install [wandio](http://research.wand.net.nz/software/libwandio.php):` the link http://research.wand.net.nz/software/libwandio.php does not work
2. `curl -LO https://research.wand.net.nz/software/wandio/wandio-4.2.3.tar.gz` gives a timeout error: `curl: (28) Failed to connect to research.wand.net.nz port 443 after 75208 ms: Operation timed out` 
   - I used this issue https://github.com/CAIDA/libbgpstream/issues/235  to download a different version of wandio instead 
   - But after downloading this version, there is no `./configure` ?

**Comment by digizeph** [comment]
For no `./configure` issue, try run `./bootstrap.sh` first.

CC @salcock for wandio site issue (`wand.net.nz` seems down too).

**Comment by jes089** [comment]
```
wandio-4.2.4-1 % ./bootstrap.sh 
./bootstrap.sh: line 7: aclocal: command not found
glibtoolize: putting auxiliary files in '.'.
glibtoolize: copying file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
./bootstrap.sh: line 20: automake: command not found
```

**Comment by salcock** [comment]
If you use brew, install automake, autoconf and libtool before running bootstrap.sh

```
brew install automake autoconf libtool
```

Sorry about the bad links -- WAND has closed down and unfortunately all of our old sites are no longer available. Some one will need to update the bgpstream instructions accordingly.

**Comment by jes089** [comment]
Thank you! That worked! I appreciate all y'all's help :D
