### ISSUE TITLE
Problem with Ubuntu 22.04

### ISSUE THREAD

**Issue by shyamkkhadka** [CAIDA/libbgpstream#238]
During installation, I got error as `E: The repository 'https://pkg.caida.org/os/ubuntu jammy Release' does not have a Release file.`, I think it doesn't have support for Ubuntu 22.04.2 version. 
![Screenshot from 2023-05-08 11-56-39](https://user-images.githubusercontent.com/129380/236794976-7860fe3f-804e-4505-a2a4-ebeabb4e7b8e.png)

**Comment by DenisKlimek** [comment]
Same here - Missing support for 22.04

**Comment by shyamkkhadka** [comment]
Please have a look into [this](https://github.com/LibtraceTeam/wandio/issues/52).

**Comment by brendonj** [comment]
Packages have now been built for Ubuntu 22.04 Jammy (as well as Debian Bullseye and Bookworm) and are available in the CAIDA package repository. If you still have the repository configured then you should be able to refresh the package index and install the package: `sudo apt-get update && sudo apt-get install bgpstream`. Let me know if you still have issues getting packages.
