### ISSUE TITLE
Ubuntu 22.04 "jammy": Unable to find package bgpstream

### ISSUE THREAD

**Issue by VCherukuri8** [CAIDA/libbgpstream#240]
<img width="633" alt="image" src="https://github.com/CAIDA/libbgpstream/assets/114771903/313f8215-56a0-4a63-89d5-60f1685fb863">

As the image and title say, I'm unable to complete the apt-get install bgpstream due to the package not being found. All dependency, wandio repo, and CAIDA repo installations went off without a hitch, its just that apt-get is not able to find the installation package for bgpstream. I checked packages.ubuntu.com, and it also was saying that it could not find any package titled "bgpstream". Is Ubuntu 22.04 not supported? Why is the package missing?

**Comment by brendonj** [comment]
Packages have now been built for Ubuntu 22.04 Jammy (as well as Debian Bullseye and Bookworm) and are available in the CAIDA package repository. If you still have the repository configured then you should be able to refresh the package index and install the package: `sudo apt-get update && sudo apt-get install bgpstream`. Let me know if you still have issues getting packages.
