### ISSUE TITLE
Ubuntu 22.04.2 - could not find pthread_yield function

### ISSUE THREAD

**Issue by dacCR** [CAIDA/libbgpstream#242]
I cannot complete the build because this function is now deprecated.
https://manpages.ubuntu.com/manpages/lunar/man3/pthread_yield.3.html

How can I get past this? I had the same problem when trying on rocky 9.

**Comment by dacCR** [comment]
No idea if this is ok but I replaced all pthread_yield text with sched_yield in 'configure' and that worked.
I ran 'configure' without errors then 'make' and 'make install' and that completed.

Again, no idea if I'm doing the right thing. Figured I've nothing to lose since I can simple restore the backup I made.

**Comment by dacCR** [comment]
Is anyone monitoring these issues? Is it ok what I've done? It seems to work.

**Comment by alistairking** [comment]
Here's a commit that removes pthread_yield usage entirely https://github.com/alistairking/libbgpstream/commit/4dd32e9c0b377415ff40093ff361dd301fc396b1

**Comment by dacCR** [comment]
Thanks.

I changed the code in the file to the one you showed but now cannot compile.

# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/src/libbgpstream-2.2.0/missing aclocal-1.16 -I m4
configure.ac:65: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:49: the top level
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:65: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal-1.16: error: autom4te failed with exit status: 1
make: *** [Makefile:442: aclocal.m4] Error 1
`

**Comment by alistairking** [comment]
You might need to re-run the bootstrapping scripts. From the README:
> If you cloned BGPStream from GitHub, you will need to run ./autogen.sh before ./configure. Depending on your operating system, the ./autogen.sh execution may require a few extra packages to run. On Ubuntu, for example, you need autogen, autoconf, and libtool installed on the system before running the command.

**Comment by dacCR** [comment]
I downloaded the source, there is no bootstrap.sh file. I believe I just went to .configure but not sure now. Have to figure it out from my history.

**Comment by alistairking** [comment]
Oh yeah, if you're patching the source you'll need to get the full code from github rather than from a distribution tarball.

**Comment by dacCR** [comment]
Sure, I can do that. Is that patch in the new source?

**Comment by brendonj** [comment]
This should now be fixed by 2bce0f679c1703ef154588782af250ccd30c012e, which is part of the 2.3.0 release. Let me know if you still have issues with the latest release.
