### ISSUE TITLE
Unable to get routeviews live data stream using BGPReader

### ISSUE THREAD

**Issue by Jackie-shi** [CAIDA/libbgpstream#247]
When I use the command `bgpreader -p routeviews-stream`, the terminal just shows `WARN: No time window specified, defaulting to live mode` and then be stuck.
I wonder is there anyone who met the same problem as well and what happened?
Thanks!

**Comment by hanskuhn** [comment]
The kafka mirroring service that provides that data had crashed. I've restart the mirror service.

Testing with `bgpreader -p routeviews-stream -R isc` and it looks like data is flowing now. 

Thanks for your report!
