### ISSUE TITLE
packages needed for autoconf

### ISSUE THREAD

**Issue by digizeph** [CAIDA/libbgpstream#41]
_From @jkldgoefgkljefogeg on Jun 5, 2017_

a few packages are needed to run ./autogen.sh. For Ubuntu/Debian, `apt-get install autogen autoconf libtool`

adding this to README.md / http://bgpstream.caida.org/docs/install/bgpstream can probably help a few people. Thanks.

_Copied from original issue: CAIDA/bgpstream#46_

**Comment by alistairking** [comment]
Fixed by #59
