### ISSUE TITLE
Issue compiling with libbgpstream

### ISSUE THREAD

**Issue by ksalamat** [CAIDA/libbgpstream#61]
I have correctly installed BGPStream and I have a python code that works correctly using it. I want to develop a C++ code using the library but keep received messages like :
Undefined symbols for architecture x86_64:
"bgpstream_start(struct_bgpstream_t*)", referenced from:
For all my calledBGPStream calls.

The library are correctly installed and referred in the linker process by -lbgpstream.

Important point I am in Mac and using Mojave. Any ideas ?

**Comment by ksalamat** [comment]
Update. When I write a C program everything is fine. When I write a C++ program and use g++ for compilation the libraries are not found. Have also checked on linux and I have similar issue !

**Comment by alistairking** [comment]
Apologies for the delayed response, I've been on vacation for the last week.

Our current headers don't explicitly support C++ (we would happily take a PR for this), so you'll need to make sure you include the bgpstream header like so:
```
extern "C" {
  #include <bgpstream.h>
}
```

**Comment by alistairking** [comment]
Was this helpful?

**Comment by ksalamat** [comment]
Hi Alistair,

That solved the issue ! Would be useful to add it as a reminder to tutorials and docs so people do not wonder about a long time like me. I reinstalled 5 times libbgpstream before resorting to asking.

Anyway many thanks

Kv

**Comment by alistairking** [comment]
Yes absolutely. I think we'll actually apply this change to the headers before the release so it will just work out of the box next time :)

I'll leave this issue open for now to remind us to make the fix.

**Comment by ksalamat** [comment]
Great ! 

Many thanks. I am beginning to use the Patricia tree and some of the utils you developed (like hashing for sets of prefixes, etc …) They are also great pieces of work.

What is annoying me currently is the issue that have with a potential memory leak. I have not yet found in the code where you do the buffer management, I want to ensure that you free the buffer when a BGP dump is processed and you move to the next one (or if there is a function in the API that does this). Unless that I will have to myself stop the bgpstream, reset the buffer and relaunch it, periodically. Many thanks if you can have a look at this problem.

Kv
