### ISSUE TITLE
Assertion Error with BGPStream v2

### ISSUE THREAD

**Issue by vgiotsas** [CAIDA/libbgpstream#64]
When I run the bgpreader version 2.0.0, it fails for some older BGP dumps, e.g.:
```
bgpreader -w 1212278400,1212364800 -c route-views2 -t updates > /dev/null

bgpreader: parsebgp_mrt.c:972: parsebgp_mrt_decode: Assertion `MRT_HDR_LEN + msg->len == nread' failed.
Aborted (core dumped)
```
It looks like it breaks when trying to read `route-views2/updates.20080601.1035.bz2` if that helps.

The same command runs fine with version 1.2.1. 

OS details:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by kenkeys** [comment]
Changed to a normal error in eaaf603b; changed to a skippable error in 4c3e483.
