### ISSUE TITLE
JSON stream long startup delay

### ISSUE THREAD

**Issue by digizeph** [CAIDA/libbgpstream#69]
Likely due to the caching by wandio, the delay between start the bgpreader for stream and the stream shows up could be very long (longer than 30s).

it's preferable to fix it by extend wandio by providing config options to allow wandio to disable threads and reduce buffers.

**Comment by alistairking** [comment]
We fixed this by creating a new "http" transport which directly uses the wandio http reader and thus avoids the thread buffers.
