### ISSUE TITLE
libbgpstream resliency against corrupted data

### ISSUE THREAD

**Issue by digizeph** [CAIDA/libbgpstream#78]
This is a catch all issue that logs problems found where libbgpstream crashes on corrupted data while it should continue going.

**Comment by digizeph** [comment]
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/routeviews/route-views.isc/updates/2004/08/10/routeviews.route-views.isc.updates.1092168420.bz2 > /dev/null
WARN: No time window specified, defaulting to all available data
2019-04-24 21:46:29 26428: bgpstream_utils_as_path.c:595: ERROR: AS_PATH with unknown segment type 1819635523
2019-04-24 21:46:29 26428: bgpstream_parsebgp_common.c:456: ERROR: Could not parse AS_PATH
2019-04-24 21:46:29 26428: bgpstream_parsebgp_common.c:373: ERROR: Could not extract path attributes
ERROR: Failed to get elem from record
```

**Comment by digizeph** [comment]
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc03/updates/2005/11/11/ris.rrc03.updates.1131719400.gz
ERROR: AS_PATH with unknown segment type 0
```

**Comment by digizeph** [comment]
Related to https://github.com/CAIDA/libparsebgp/issues/49

**Comment by digizeph** [comment]
I think this error is potentially caused by corrupted data. However, the AS path attributes were parsed in `bgpstream_utils_as_path.c` rather than `libparsebgp`, making it has different behavior when encounter corrupted data. I think this should be fixed by handling such error the same way it handles libparsebgp return code.

**Comment by kenkeys** [comment]
I got rid of "ERROR: AS_PATH with unknown segment type 0" in 26a41f3.

**Comment by alistairking** [comment]
Closing until/unless we find more parsing issues
