### ISSUE TITLE
The constant PARSEBGP_TRUNCATED_MSG is not defined

### ISSUE THREAD

**Issue by Nebla** [CAIDA/libbgpstream#92]
When trying to compile from source code libbgpstream-2.0.0, I get this error message on "make" step.

```
bgpstream_parsebgp_common.c: In function ‘bgpstream_parsebgp_populate_record’:
bgpstream_parsebgp_common.c:589:23: error: ‘PARSEBGP_TRUNCATED_MSG’ undeclared (first use in this function)
     } else if (err == PARSEBGP_TRUNCATED_MSG) {
                       ^
bgpstream_parsebgp_common.c:589:23: note: each undeclared identifier is reported only once for each function it appears in
```

I search for it on the github repo and found out that this piece of code was included on this commit https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f but it seems that the variable was never defined. I tried removing that piece of code and everything seems to be working fine, altought I probably do not execute that code never.

**Comment by alistairking** [comment]
@kenkeys is it possible that we're including a previously-installed version of the header instead of the new (local) version?

**Comment by Nebla** [comment]
I checked in the submodule, and it seems that is properly defined on libparsebgp/lib/parsebgp_error.h
on commit  4c3e48 which is the one defined on the submodule. Could it be that the tar.gz uploaded http://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/pybgpstream-2.0.0-beta-3.tar.gz  isn't considering the submodule properly?

**Comment by digizeph** [comment]
Thanks for bring up this issue. I can confirm this issue happens on a fresh VM. I'm working on fix this now.

**Comment by digizeph** [comment]
Hi @Nebla, the problem should be fixed now. If you download the new tarball at
http://bgpstream.caida.org/bundles/caidabgpstreamwebhomepage/dists/libbgpstream-2.0.0-beta-6.tar.gz (or at the [release][1] page at this repo), you should be able to build it.

Please let use know if you still have any problems building or have encountered any other issues. Thanks!

[1]:https://github.com/CAIDA/libbgpstream/releases/tag/v2.0-beta-6
